package com.vermouthx.stocker.finance

import java.nio.file.Path
import java.time.LocalDate

/**
 * Parses today's daily-coordinator.md (machine-generated by
 * tools/generate_coordinator_schedule.py — v2.9 SessionStart hook).
 *
 * Markdown structure (excerpt):
 *   # 每日调度清单 (机械版) — 2026-05-23 (DOW=6)
 *   ## 决策上下文
 *   - 市场状态：非交易日
 *   - 持仓数：0 只
 *   - watchlist 主线数：9
 *   ## 今日调度（按并行组）
 *   ### 组 A：盘前
 *   - ✅ overnight-brief
 *   - ⏭️ news-radar  (last 0d)
 *   ## 跳过项
 *   - ⏭️ daily-review（非交易日）
 *   ## 判断快照
 *   ```yaml ... ```
 *
 * For the banner we want a compact "今日还该跑啥 / 已跑啥 / 跳过啥" rollup.
 */
data class CoordinatorSchedule(
    val date: LocalDate,
    val isTradingDay: Boolean?,
    val dow: Int?,
    val holdingsCount: Int?,
    val watchlistThreads: Int?,
    val upcomingCatalysts: List<String>,
    /** agent → status emoji (✅ done / ⏳ pending / ⏭️ skipped) */
    val agentStatus: List<AgentRow>,
) {
    data class AgentRow(val groupName: String, val agent: String, val statusEmoji: String, val note: String?)

    val doneCount: Int get() = agentStatus.count { it.statusEmoji == "✅" }
    val pendingCount: Int get() = agentStatus.count { it.statusEmoji == "⏳" }
    val skippedCount: Int get() = agentStatus.count { it.statusEmoji == "⏭️" }
}

internal object FinanceDailyCoordinatorLoader {

    fun load(financeDir: Path, today: LocalDate = FinanceReportLocator.today()): CoordinatorSchedule? {
        for (b in 0..3) {
            val d = today.minusDays(b.toLong())
            val md = FinanceReportLocator.readReport(financeDir, "daily-coordinator", d) ?: continue
            return parse(md, d)
        }
        return null
    }

    private fun parse(md: String, date: LocalDate): CoordinatorSchedule {
        val lines = md.lines()

        // ── Context block (## 决策上下文) ────────────────────────────────
        var isTradingDay: Boolean? = null
        var dow: Int? = null
        var holdings: Int? = null
        var threads: Int? = null
        val catalysts = ArrayList<String>()

        var inContext = false
        var inCatalysts = false
        for (line in lines) {
            val t = line.trim()
            if (t.startsWith("## ")) {
                inContext = t.contains("决策上下文")
                inCatalysts = false
            }
            if (inContext) {
                if (t.contains("市场状态")) {
                    isTradingDay = !t.contains("非交易")
                }
                if (t.contains("持仓数")) {
                    HOLDINGS_RE.find(t)?.let { holdings = it.groupValues[1].toIntOrNull() }
                }
                if (t.contains("watchlist 主线数")) {
                    THREAD_RE.find(t)?.let { threads = it.groupValues[1].toIntOrNull() }
                }
                if (t.contains("upcoming-catalysts")) {
                    inCatalysts = true
                    continue
                }
                if (inCatalysts && t.startsWith("- ") && !t.contains("upcoming-catalysts")) {
                    catalysts.add(t.removePrefix("- "))
                } else if (inCatalysts && !t.startsWith("- ") && t.isNotBlank()) {
                    inCatalysts = false
                }
            }
            if (t.startsWith("- DOW=") || t.contains("DOW=")) {
                DOW_RE.find(t)?.let { dow = it.groupValues[1].toIntOrNull() }
            }
        }
        // DOW also appears in the H1 — fallback
        if (dow == null) {
            for (line in lines) {
                DOW_HEADER_RE.find(line)?.let {
                    dow = it.groupValues[1].toIntOrNull()
                    return@let
                }
                if (dow != null) break
            }
        }

        // ── 今日调度 + 跳过项 ────────────────────────────────────────────
        val rows = ArrayList<CoordinatorSchedule.AgentRow>()
        var curGroup = "默认"
        var inSchedule = false
        var inSkipped = false
        for (line in lines) {
            val t = line.trim()
            if (t.startsWith("## ")) {
                inSchedule = t.contains("今日调度")
                inSkipped = t.contains("跳过项") || t.contains("跳过")
                continue
            }
            if (t.startsWith("### ") && inSchedule) {
                curGroup = t.removePrefix("### ").trim()
                continue
            }
            if (inSchedule || inSkipped) {
                AGENT_LINE_RE.find(t)?.let { m ->
                    val emoji = m.groupValues[1]
                    val agentRaw = m.groupValues[2].trim()
                    // Strip parenthetical note from agent name
                    val parts = agentRaw.split(Regex("""\s*[（(]""")).map { it.trim() }
                    val agent = parts.firstOrNull() ?: agentRaw
                    val note = if (parts.size > 1) parts.drop(1).joinToString("(").trimEnd(')', '）') else null
                    rows.add(
                        CoordinatorSchedule.AgentRow(
                            groupName = if (inSkipped) "跳过" else curGroup,
                            agent = agent,
                            statusEmoji = emoji,
                            note = note,
                        )
                    )
                }
            }
        }

        return CoordinatorSchedule(
            date = date,
            isTradingDay = isTradingDay,
            dow = dow,
            holdingsCount = holdings,
            watchlistThreads = threads,
            upcomingCatalysts = catalysts,
            agentStatus = rows,
        )
    }

    // Recognise "- ✅ overnight-brief" / "- ⏭️ ..." / "- ⏳ macro-radar"
    private val AGENT_LINE_RE = Regex("""^[-\*]\s+(✅|⏳|⏭️|⏸️|🟢|🟡|🔴)\s+([^\n]+)""")
    private val HOLDINGS_RE = Regex("""(\d+)\s*只""")
    private val THREAD_RE = Regex("""(\d+)""")
    private val DOW_RE = Regex("""DOW=(\d)""")
    private val DOW_HEADER_RE = Regex("""DOW=(\d)""")
}
